export let quotes = [
    "Life is too short to waste time on things that don't matter.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Be the change you wish to see in the world.",
    "Believe you can and you're halfway there.",
    "Don't let yesterday take up too much of today.",
    "You can't change the past, but you can shape the future.",
    "Life is a journey, not a destination.",
    "Strive not to be a success, but rather to be of value.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "It is not in the stars to hold our destiny but in ourselves.",
    "The only way to do great work is to love what you do.",
    "You miss 100% of the shots you don't take.",
    "The best way to predict the future is to create it.",
    "Don't wait for opportunity. Create it.",
    "It always seems impossible until it's done.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "A journey of a thousand miles begins with a single step.",
    "In the middle of difficulty lies opportunity.",
    "If you want to lift yourself up, lift up someone else.",
    "Don't watch the clock; do what it does. Keep going.",
    "We become what we think about.",
    "If you can dream it, you can achieve it.",
    "Change your thoughts and you change your world.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Your only limit is the amount of willingness you have to learn and grow.",
    "To succeed, we must first believe that we can.",
    "You don't have to be great to start, but you have to start to be great.",
    "Life is not about waiting for the storm to pass, it's about learning to dance in the rain.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The mind is everything. What you think you become.",
    "The journey of a thousand miles begins with one step.",
    "Don't count the days, make the days count.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.",
    "The best preparation for tomorrow is doing your best today.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "It's not the years in your life that count. It's the life in your years.",
    "Be yourself; everyone else is already taken.",
    "If you want to achieve greatness, stop asking for permission.",
    "Be the best version of yourself.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Never let the circumstances of the moment define your life's path.",
    "Don't be afraid to fail. Be afraid not to try.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Do what you can, with what you have, where you are.",
    "If you don't like something, change it. If you can't change it, change your attitude.",
    "The greatest wealth is to live content with little.",
    "The only true wisdom is in knowing you know nothing.",
    "The difference between ordinary and extraordinary is that little extra.",
    "The only way to have a good day is to start it with a positive attitude.",
    "Life is a gift. Never forget to enjoy and bask in every moment you are in.",
    "Happiness is not the absence of problems, it's the ability to deal with them.",
    "Believe in the power of your dreams.",
    "The only impossible journey is the one you never begin.",
    "Stay focused, stay positive, stay strong, and everything will fall into place.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "The only limits in life are the ones you set for yourself.",
    "Success is not the destination, it's the journey.",
    "Be kind whenever possible. It is always possible.",
    "A person who never made a mistake never tried anything new.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Life is either a daring adventure or nothing at all.",
    "Never regret anything that made you smile.",
    "If opportunity doesn't knock, build a door.",
    "The only way to have a friend is to be one.",
    "Life is too short to be anything but happy.",
    "Happiness is not a destination, it's a journey.",
    "The best way out is always through.",
    "You are never too old to set another goal or to dream a new dream.",
    "Believe that you can and you're halfway there.",
    "The only thing we have to fear is fear itself.",
    "When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.",
    "We must be the change we wish to see in the world.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "We can't help everyone, but everyone can help someone.",
    "Nothing is impossible, the word itself says 'I'm possible'!",
    "If you want to change the world, change yourself first.",
    "Be the reason someone smiles today.",
    "Do not let what you cannot do interfere with what you can do.",
    "You can have everything in life you want, if you will just help other people get what they want.",
    "Believe in yourself and you can accomplish anything.",
    "In a gentle way, you can shake the world."
]